AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Crawlers for Airline & Customers

Resources:
  AirlineCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: airline
      Role: arn:aws:iam::808887184367:role/AWSGlueServiceRoleDefault
      DatabaseName: airline_db
      Targets:
        S3Targets:
          - Path: s3://airport-airline-operations-analytics-platform/airline/
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  CustomersCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: customers
      Role: arn:aws:iam::808887184367:role/AWSGlueServiceRoleDefault
      DatabaseName: airline_db
      Targets:
        S3Targets:
          - Path: s3://airport-airline-operations-analytics-platform/customers/
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
